swagger: '2.0'
info:
  version: '1.0'
  title: "SmartCinema"
  description: "Progetto di INGSOFT 2 - 2020"
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: polls.apiblueprint.org
basePath: /api/v1
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /admin/login:
    x-summary: Login
    post:
      summary: Send login data
      parameters:
        - name: admin
          in: body
          required: true
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
                description: "Username of the admin"
              password:
                type: string
                description: "Password of the admin"
      responses:
        200:
          description: Logged in correctly
          schema:
            $ref: '#/definitions/LogInAdminDTO'
        400:
          description: User or password not specified
        401:
          description: Admin not logged in correctly
        
          
  /admin/fares:
    get:
      summary: "List all the tickets' fares"
      responses:
        200:
          description: "Collection of tickets' fares"
          schema:
            type: array
            items:
              $ref: "#/definitions/FareDTO"
        401:
          description: Admin not logged in
        403:
          description: Not authorized to do this action
    post:
      summary: "Add a new tickets' fare"
      parameters:
        - in: body
          name: fare
          required: true
          
          schema:
            type: object
            required:
              - name
              - price
              - desc
        
            properties:
              name:
                type: string
                description: "fare's name"
              price: 
                type: number
                description: "fare's price"
              desc:
                type: string
                description: "fare's description"
          
      responses:
        201:
          description: 'Successful add, the fare added'
          schema:
              $ref: '#/definitions/FareDTO'
        400:
          description: Some fields are null or empty
        401:
          description: Admin not logged in
        403:
          description: Not authorized to do this action
          
  /admin/fares/{fareId}:
    parameters:
    - name: "fareId"
      in: "path"
      description: "id of the fare"
      required: true
      type: "integer"
      format: "int32"
    delete:
      summary: "Delete a fare"
      responses:
        200:
          description: Successful response
        400:
          description: fareId is NaN or empty
        401:
          description: Admin not logged in
        403:
          description: Not authorized to do this action
        404:
          description: Fare not found
        409:
          description: "Conflict: cannot delete a Fare if it is the only one left"
  
  /admin/rooms:
    get:
      summary: "List all cinema's rooms"
      responses:
        200:
          description: "Collection of cinema's rooms"
          schema:
            type: array
            items:
              $ref: "#/definitions/CinemaRoomDTO"
        401:
          description: Admin not logged in
        403:
          description: Not authorized to do this action
    post:
      summary: "Add a new cinema's room"
      parameters:
        - in: body
          name: room
          required: true
          
          schema:
            type: object
            required:
              - name
        
            properties:
              name:
                type: string
                description: "room's name"
          
      responses:
        201:
          description: 'Successful add, room added'
          schema:
              $ref: '#/definitions/CinemaRoomDTO'
        400:
          description: Some fields are null or empty
        401:
          description: Admin not logged in
        403:
          description: Not authorized to do this action
          
  /admin/rooms/{roomId}:
    parameters:
    - name: "roomId"
      in: "path"
      description: "id of the cinema's room"
      required: true
      type: "integer"
      format: "int32"
    put:
      summary: Update a cinema's room
      parameters:
        - in: body
          name: room
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: "Room's name"
      responses:
        200:
          description: "Successful update, cinema's room update"
          schema:
            $ref: '#/definitions/CinemaRoomDTO'
        400:
          description: Some fields are null or empty
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
        404:
          description: Cinema's room not found
          
    delete:
      summary: "Delete a cinema room"
      responses:
        200:
          description: Successful response, room deleted
        400:
          description: roomId is NaN or empty
        401:
          description: Admin not logged in
        403:
          description: Not authorized to do this action
        404:
          description: Cinema's room not found
        409:
          description: "Conflict: cannot delete a room with active reservations or actions"
  
  /admin/rooms/{roomId}/rows:
    parameters:
    - name: "roomId"
      in: "path"
      description: "id of the cinema's room"
      required: true
      type: "integer"
      format: "int32"
    get:
      summary: "List all rows of a room"
      responses:
        200:
          description: "Collection of room's row"
          schema:
            type: array
            items:
              $ref: "#/definitions/RoomRowDTO"
        401:
          description: Admin not logged in
        403:
          description: Not authorized to do this action
    post:
      summary: "Add a new row to a room"
      parameters:
        - in: body
          name: room
          required: true
          schema:
            type: object
            required:
              - seatsNumber
        
            properties:
              seatsNumber:
                type: integer
                description: "row seats"
      responses:
        201:
          description: 'Successful add, row added'
          schema:
              $ref: '#/definitions/RoomRowDTO'
        400:
          description: Some fields are null or empty
        401:
          description: Admin not logged in
        403:
          description: Not authorized to do this action
  
  /admin/movies:
    get:
        summary: "List all the movies"
        responses:
          200:
            description: "Collection of movies"
            schema:
              type: array
              items:
                $ref: "#/definitions/MovieDTO"
          401:
            description: Admin not logged in
          403:
            description: Not authorized to do this action
    post:
        summary: "Add a new Movie"
        parameters:
          - in: body
            name: movie
            required: true
            
            schema:
              type: object
              required:
                - imageUrl
                - title
                - desc
          
              properties:
                title:
                  type: string
                  description: "movie's name"
                imageUrl: 
                  type: string
                  description: "movie's image"
                desc:
                  type: string
                  description: "movie's description"
            
        responses:
          201:
            description: 'Successful add, the movie added'
            schema:
                $ref: '#/definitions/MovieDTO'
          400:
            description: Some fields are null or empty
          401:
            description: Admin not logged in
          403:
            description: Not authorized to do this action
    
  /admin/movies/:{movieId}/plannings:
    parameters:
    - name: "movieId"
      in: "path"
      description: "id of the movie"
      required: true
      type: "integer"
      format: "int32"
    post:
        summary: "Add plannings for a movie"
        parameters:
          - in: body
            name: planning
            required: true
            
            schema:
              type: object
              required:
                - plannings
          
              properties:
                plannings:
                  type: array
                  items:
                    type: object
                    required:
                      - roomId
                      - date
                    properties:
                      roomId:
                        type: number
                        description: "Movie's room"
                      date:
                        type: string
                        format: date-time
                        description: "Movie's date time"
                  description: "Movie's plannings"
        responses:
          201:
            description: 'Successful add, movie plannings added'
            schema:
                $ref: '#/definitions/PlanningDTO'
          400:
            description: Some fields are null or empty
          401:
            description: Admin not logged in
          403:
            description: Not authorized to do this action

definitions:
  PlanningDTO:
    type: object
    required:
      - room
      - date
    
    properties:
        planningId:
          type: number
          description: "Movie's planning"
        room:
          type: object
          $ref: "#/definitions/CinemaRoomDTO"
          description: "Movie's room"
        date:
          type: string
          format: date-time
          description: "Movie's date time"
  
  MovieDTO:
    type: object
    required:
      - movieId
      - imageUrl
      - title
      - desc
      - planning
      
    properties:
        movieId:
          type: number
          description: "Movie's Id"
        imageUrl:
          type: string
          description: "Movie's image Url"
        title:
          type: string
          description: "Movie's title"
        desc:
          type: string
          description: "Movie desc"
        planning:
          type: array
          items:
             $ref: "#/definitions/PlanningDTO"
          description: "Movie's plannings"

  LogInAdminDTO:
    type: object
    required:
      - token
      - username

    properties:
      token:
        type: string
        description: 'token'
      username:
        type: string
        description: 'Admin username'

  FareDTO:
    type: object
    required:
      - fareId
      - name
      - price
      - desc
      
    properties:
      fareId:
        type: integer
        format: "int32"
        description: "fare's id"
      name:
        type: string
        description: "fare's name"
      price: 
        type: number
        description: "fare's price"
      desc:
        type: string
        description: "fare's description"
  
  RoomRowDTO:
    type: object
    required:
      - rowId
      - seatsNumber

    properties:
      rowId:
        type: integer
        format: "int32"
        description: "room's id"
      seatsNumber: 
        type: number
        description: "number of seats"

  CinemaRoomDTO:
    type: object
    required:
      - roomId
      - name
      - seats

    properties:
      roomId:
        type: integer
        format: "int32"
        description: "room's id"
      name:
        type: string
        description: "room's name"
      seats: 
        type: number
        description: "number of seats"