swagger: '2.0'
info:
  version: '1.0'
  title: "SmartCinema"
  description: "Progetto di INGSOFT 2 - 2020"
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: polls.apiblueprint.org
basePath: /api
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /v1/admin/login:
    x-summary: Login
    post:
      summary: Send login data
      parameters:
        - name: admin
          in: body
          required: true
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
                description: "Username of the admin"
              password:
                type: string
                description: "Password of the admin"
      responses:
        200:
          description: Logged in correctly
          schema:
            $ref: '#/definitions/LogInAdminDTO'
        401:
          description: Admin not logged in correctly
          
  /v1/admin/fares:
    get:
      summary: "List all the tickets' fares"
      responses:
        200:
          description: "Collection of tickets' fares"
          schema:
            type: array
            items:
              $ref: "#/definitions/FareDTO"
        401:
          description: Admin not logged in
        403:
          description: Not authorized to do this action
    post:
      summary: "Add a new tickets' fare"
      parameters:
        - in: body
          name: fare
          required: true
          
          schema:
            type: object
            required:
              - name
              - price
              - desc
        
            properties:
              name:
                type: string
                description: "fare's name"
              price: 
                type: number
                description: "fare's price"
              desc:
                type: string
                description: "fare's description"
          
      responses:
        201:
          description: 'Successful add, the fare added'
          schema:
              $ref: '#/definitions/FareDTO'
        401:
          description: Admin not logged in
        403:
          description: Not authorized to do this action
          
  /v1/admin/fares/{fareId}:
    parameters:
    - name: "fareId"
      in: "path"
      description: "id of the fare"
      required: true
      type: "integer"
      format: "int32"
    delete:
      summary: "Delete a fare"
      responses:
        200:
          description: Successful response
        401:
          description: Admin not logged in
        403:
          description: Not authorized to do this action
        404:
          description: Fare not found
          
definitions:
  LogInAdminDTO:
    type: object
    required:
      - token
      - username

    properties:
      token:
        type: string
        description: 'token'
      username:
        type: string
        description: 'Admin username'
        
        
  FareDTO:
    type: object
    required:
      - fareId
      - name
      - price
      - desc
      
    properties:
      fareId:
        type: integer
        format: "int32"
        description: "fare's id"
      name:
        type: string
        description: "fare's name"
      price: 
        type: number
        description: "fare's price"
      desc:
        type: string
        description: "fare's description"