swagger: '2.0'
info:
  version: '1.0'
  title: "SmartCinema"
  description: "Progetto di INGSOFT 2 - 2020"
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: polls.apiblueprint.org
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /v1/admin/login:
    x-summary: Login
    post:
      summary: Send login data
      parameters:
        - name: admin
          in: body
          required: true
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
                description: 'Username of the admin'
              password:
                type: string
                description: 'Password of the admin'
      responses:
        200:
          description: Logged in correctly
          schema:
            $ref: '#/definitions/LogInAdminDTO'
        401:
          description: Admin not logged in correctly
          
definitions:
  LogInAdminDTO:
    type: object
    required:
      - token
      - username

    properties:
      token:
        type: string
        description: 'token'
      username:
        type: string
        description: 'Admin username'