const STORE_TOKEN = 'STORE_TOKEN';
const SET_ROLE = 'SET_ROLE';
const SET_USERNAME = 'SET_USERNAME';
const SET_AUTH_STATE = 'SET_AUTH_STATE';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const READ_TOKEN = 'READ_TOKEN';
const SET_USER = 'SET_USER';
const READ_USER = 'READ_USER';

export {
  READ_TOKEN,
  STORE_TOKEN,
  SET_ROLE,
  SET_USERNAME,
  SET_AUTH_STATE,
  LOGIN,
  LOGOUT,
  SET_USER,
  READ_USER
};